# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ranwuer
email: ranwuer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  网站架构设计，C/C++，DBA，PHP，算法，ACM。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ranwuer.com" # the base hostname & protocol for your site
twitter_username: ranwuer
github_username:  ranwu
permalink: pretty

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-80732671-1